# -*- coding: utf-8 -*-
"""Untitled14.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1r_vRjQVRzBHfD5Qrr9cPm4y5bQYG9JcR
"""

import streamlit as st
import numpy as np
from scipy.stats import norm

# Funções auxiliares
def bs_call_price(S, K, T, r, sigma):
    d1 = (np.log(S / K) + (r + 0.5 * sigma ** 2) * T) / (sigma * np.sqrt(T))
    d2 = d1 - sigma * np.sqrt(T)
    return S * norm.cdf(d1) - K * np.exp(-r * T) * norm.cdf(d2)

def implied_vol_bisection(C_market, S, K, T, r, tol=1e-5, max_iter=100):
    low = 1e-5
    high = 3.0
    for i in range(max_iter):
        mid = (low + high) / 2
        price = bs_call_price(S, K, T, r, mid)
        if abs(price - C_market) < tol:
            return mid
        elif price > C_market:
            high = mid
        else:
            low = mid
    return mid

def monte_carlo_option_price(S, K, T, r, sigma, tipo='europeia', num_sim=10000):
    np.random.seed(42)
    dt = T
    if tipo == 'europeia':
        ST = S * np.exp((r - 0.5 * sigma ** 2) * dt + sigma * np.sqrt(dt) * np.random.randn(num_sim))
        payoff = np.maximum(ST - K, 0)
    elif tipo == 'asiatica':
        dt = T / 100
        steps = int(T / dt)
        ST = np.zeros(num_sim)
        for i in range(num_sim):
            prices = S * np.exp(np.cumsum((r - 0.5 * sigma ** 2) * dt +
                                          sigma * np.sqrt(dt) * np.random.randn(steps)))
            ST[i] = np.mean(prices)
        payoff = np.maximum(ST - K, 0)
    return np.exp(-r * T) * np.mean(payoff)

# App Streamlit
st.title("Calculadora de Opções e Volatilidade Implícita")

opcao = st.sidebar.selectbox("Escolha a operação", ["Preço da Opção", "Volatilidade Implícita"])

if opcao == "Preço da Opção":
    tipo = st.selectbox("Tipo de Opção", ["Europeia", "Asiática"])
    S = st.number_input("Preço do ativo (S)", min_value=0.01)
    K = st.number_input("Strike (K)", min_value=0.01)
    T = st.number_input("Tempo até o vencimento (em anos)", min_value=0.01)
    r = st.number_input("Taxa de juros (r)", min_value=0.0)
    sigma = st.number_input("Volatilidade (σ)", min_value=0.01)

    if st.button("Calcular Preço"):
        preco = monte_carlo_option_price(S, K, T, r, sigma, tipo=tipo.lower())
        st.success(f"Preço estimado da opção {tipo.lower()}: R$ {preco:.2f}")

elif opcao == "Volatilidade Implícita":
    C_market = st.number_input("Preço de mercado da opção (C)", min_value=0.01)
    S = st.number_input("Preço do ativo (S)", min_value=0.01)
    K = st.number_input("Strike (K)", min_value=0.01)
    T = st.number_input("Tempo até o vencimento (em anos)", min_value=0.01)
    r = st.number_input("Taxa de juros (r)", min_value=0.0)

    if st.button("Calcular Volatilidade"):
        vol = implied_vol_bisection(C_market, S, K, T, r)
        st.success(f"Volatilidade implícita estimada: {vol:.4f}")